#!/usr/bin/env bash
# Local databases for satus. Nothing here talks to the hosted Supabase
# project or to https://satus.sh.
#
#   scripts/test-db.sh           start (or reuse) the stack and write .env.local
#   scripts/test-db.sh --reset   replay all migrations and the synthetic seed
#
# Supabase local DB is 127.0.0.1:54322. The CLI throwaway (pagila on
# pgvector/pgvector:pg18) is 127.0.0.1:5432, matching action-selftest.yml.
# DATABASE_URL in .env.local points at that throwaway, never at production.
set -euo pipefail

export DO_NOT_TRACK=1
export SUPABASE_TELEMETRY_DISABLED=1
export PATH="/opt/satus-toolchain/bin:/usr/local/bin:${PATH}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESET=0
if [[ "${1:-}" == "--reset" ]]; then
  RESET=1
elif [[ -n "${1:-}" ]]; then
  echo "usage: scripts/test-db.sh [--reset]" >&2
  exit 2
fi

PAGILA_NAME=satus-pagila
PAGILA_URL="postgres://postgres:postgres@127.0.0.1:5432/pagila"
# Fixture only. Not a Stripe secret. The local dev server uses this to
# reject bad signatures and stale timestamps. Never send those requests
# anywhere except 127.0.0.1.
WEBHOOK_FIXTURE="local-sandbox-webhook-fixture"

ensure_docker() {
  sudo sysctl -q -w net.bridge.bridge-nf-call-iptables=0
  sudo sysctl -q -w net.bridge.bridge-nf-call-ip6tables=0

  if docker info >/dev/null 2>&1; then
    return 0
  fi

  sudo mkdir -p /etc/docker
  if [[ ! -f /etc/docker/daemon.json ]]; then
    sudo tee /etc/docker/daemon.json >/dev/null <<'EOF'
{
  "storage-driver": "fuse-overlayfs",
  "exec-opts": ["native.cgroupdriver=cgroupfs"],
  "iptables": true,
  "ip6tables": false,
  "live-restore": false
}
EOF
  fi

  if ! pgrep -x dockerd >/dev/null 2>&1; then
    sudo mkdir -p /var/lib/docker /var/run
    if tmux has-session -t dockerd 2>/dev/null; then
      tmux kill-session -t dockerd
    fi
    tmux new-session -d -s dockerd -- \
      bash -lc "sudo dockerd --host=unix:///var/run/docker.sock >>/tmp/dockerd.log 2>&1"
  fi

  local _
  for _ in $(seq 1 30); do
    if [[ -S /var/run/docker.sock ]]; then
      sudo chmod 666 /var/run/docker.sock || true
      if docker info >/dev/null 2>&1; then
        return 0
      fi
    fi
    sleep 1
  done
  echo "dockerd did not become ready; see /tmp/dockerd.log" >&2
  tail -n 40 /tmp/dockerd.log >&2 || true
  exit 1
}

ensure_pagila() {
  if ! docker ps --format '{{.Names}}' | grep -qx "$PAGILA_NAME"; then
    if docker ps -a --format '{{.Names}}' | grep -qx "$PAGILA_NAME"; then
      docker start "$PAGILA_NAME" >/dev/null
    else
      docker run -d --name "$PAGILA_NAME" \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres \
        -e POSTGRES_DB=pagila \
        -p 5432:5432 \
        pgvector/pgvector:pg18 >/dev/null
    fi
  fi

  local _
  for _ in $(seq 1 60); do
    if PGPASSWORD=postgres pg_isready -q -h 127.0.0.1 -p 5432 -U postgres; then
      break
    fi
    sleep 1
  done
  PGPASSWORD=postgres pg_isready -q -h 127.0.0.1 -p 5432 -U postgres

  local has_customer
  has_customer="$(PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d pagila -Atc \
    "select to_regclass('public.customer') is not null")"
  if [[ "$has_customer" == "t" ]]; then
    return 0
  fi

  # Same commit the action self-test loads. Not production data.
  curl -fsSL https://raw.githubusercontent.com/devrimgunduz/pagila/9baf49c4149e43229f6021e6218d6b2ac8ef4f34/pagila-schema.sql \
    -o /tmp/pagila-schema.sql
  PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d pagila -v ON_ERROR_STOP=1 \
    -f /tmp/pagila-schema.sql >/dev/null
  PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -d pagila -v ON_ERROR_STOP=1 \
    -c "CREATE TABLE IF NOT EXISTS payment_pdefault PARTITION OF payment DEFAULT;" >/dev/null
}

write_env() {
  local status tmp
  status="$(supabase status -o env)"
  tmp="$(mktemp)"
  umask 077
  {
    echo "# Generated by scripts/test-db.sh. Gitignored. Local stack only."
    echo "DATABASE_URL=${PAGILA_URL}"
    echo "PAYMENTS_SANDBOX_WEBHOOK_SECRET=${WEBHOOK_FIXTURE}"
    while IFS= read -r line; do
      case "$line" in
        API_URL=*|ANON_KEY=*|SERVICE_ROLE_KEY=*|PUBLISHABLE_KEY=*) ;;
        *) continue ;;
      esac
      local key="${line%%=*}"
      local val="${line#*=}"
      val="${val%\"}"
      val="${val#\"}"
      case "$key" in
        API_URL)
          echo "SUPABASE_URL=${val}"
          echo "VITE_SUPABASE_URL=${val}"
          ;;
        PUBLISHABLE_KEY)
          echo "VITE_SUPABASE_PUBLISHABLE_KEY=${val}"
          echo "SUPABASE_PUBLISHABLE_KEY=${val}"
          ;;
        SERVICE_ROLE_KEY)
          echo "SUPABASE_SERVICE_ROLE_KEY=${val}"
          ;;
      esac
    done <<<"$status"
  } >"$tmp"
  mv "$tmp" "$ROOT/.env.local"
  chmod 600 "$ROOT/.env.local"
}

cd "$ROOT"
ensure_docker
ensure_pagila

if [[ "$RESET" -eq 1 ]]; then
  supabase start >/tmp/supabase-start.log
  supabase --yes db reset --local >>/tmp/supabase-start.log
else
  supabase start >/tmp/supabase-start.log
fi

write_env

migrations="$(PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -Atc \
  "select count(*) from supabase_migrations.schema_migrations")"
seed="$(PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -Atc \
  "select count(*) from public.licenses where email = 'local-seed@example.test'")"
e2e_cron="$(PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -Atc \
  "select count(*) from cron.job where jobname = 'satus-e2e-health-daily'")"

echo "supabase_api=http://127.0.0.1:54321"
echo "supabase_db=postgresql://postgres@127.0.0.1:54322/postgres"
echo "DATABASE_URL=${PAGILA_URL}"
echo "migrations=${migrations}"
echo "seed_licenses=${seed}"
echo "production_e2e_cron_jobs=${e2e_cron}"
echo "env_file=.env.local"
